.TH fv 1 "16-6-2020" "version 1.0" "fv Manual"

.SH NAME
fv - A command line file pager.

.SH SYNOPSIS
fv is a simple command line file page written as a learning exercise. It has vim like keybinds and a minimal status bar.

.SH USAGE
.B fv
<filename>[:<line-number>] [-l] [-h] [-v]

.SH OPTIONS
.IP <filename>:[<line-number>]
Name of the file to view. To open the file at a specific line, append ":" and line number to filename.
.IP -l
Disable line numbers.
.IP -h
Show usage.
.IP -v
Print version.

.SH KEYBINDINGS
.IP h
Scroll left a column.
.IP j
Scroll down a row.
.IP k
Scroll up a row.
.IP l
Scroll right a column.
.IP g
Scroll to top of the file.
.IP G
Scroll to bottom of the file.
.IP $
Scroll to end of the largest line.
.IP ^
Scroll to state of line.
.IP q
Exit fv.
.IP <num><key>RETURN
<key> can be one of h,j,k,l. Scroll num rows or columns based on the key.
.IP <num>RETURN
Scroll to line number num. If if doesn't exist, scroll to bottom.

.SH FILES
.I /usr/local/bin/fv
.br
.I /usr/local/man/man1/fv

.SH PROJECT LOCATION
.I https://github.com/saivarshith2000/fv

.SH BUGS
If you find any bugs, please feel free to create an issue at
.I https://github.com/saivarshith2000/fv/issues

.SH AUTHOR
Sai Varshith (hosvarshith@gmail.com)

.SH COPYRIGHT
2020, Sai Varshith (hosvarshith@gmail.com)
